name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Display test status badge
            run: echo "![Test Status](https://github.com/cu-ecen-aeld/assignment-1-dnagalla/actions/workflows/github-actions.yml/badge.svg)"
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:24-assignment1
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Display test status badge
            run: echo "![Test Status](https://github.com/cu-ecen-aeld/assignment-1-dnagalla/actions/workflows/github-actions.yml/badge.svg)"
          - name: Run full test
            run: ./full-test.sh
